# Generated by Django 5.0.6 on 2024-12-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LUN', '0002_team_country_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='api_id',
            field=models.IntegerField(default=0, null=True, unique=True),
        ),
    ]
