# Generated by Django 5.0.6 on 2024-12-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LUN', '0004_alter_player_height_alter_player_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='api_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='matchstat',
            name='api_id',
            field=models.IntegerField(default=None, null=True, unique=True),
        ),
    ]
