# Generated by Django 5.1.4 on 2024-12-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LUN', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='goal_difference',
            field=models.IntegerField(default=0),
        ),
    ]
